name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thanks for raising the issue it will definitely improve our quality'' first issue'
        pr-message: 'Hurrahhh!! You made your first PR, good job carryon!'' first pr'
